"""Structured dependency analysis for selected forward and derivative outputs.

A consumer that wants to run a generated derivative program must bind one value
for every free input of that program. Discovering those inputs by scanning graph
nodes, consulting a private producer map, or reading meaning into how a value id
happens to be spelled makes the consumer responsible for graph mechanics that
belong to the framework. This module owns that responsibility instead.

Analysis starts from explicitly selected outputs, traverses only the nodes those
outputs reach, and reports every value the selection depends on together with a
provenance category and normalized type metadata:

``declared_input``
    A value the forward trace declared as a named graph input. The consumer
    supplies it (parameters, training data, labels).
``seed_input``
    An upstream cotangent generated by the derivative transform. The consumer
    supplies it, typically as ones shaped like the differentiated output.
``forward_capture``
    An intermediate produced by the forward graph and consumed again by the
    derivative program. The consumer must execute the forward graph and retain
    it before running the derivative program.
``local_value``
    A value produced inside the analyzed selection itself. Nothing to bind.

Provenance is decided structurally, from where a value is produced relative to
the forward graph and the declared seeds, never from its id text. Ordering is
deterministic and documented: dependencies are grouped in
:data:`DEPENDENCY_PROVENANCE_ORDER`, declared inputs follow forward-graph
declaration order, seeds follow the order the caller declared them, forward
captures follow forward-graph topological order, and local values follow the
topological order of the analyzed selection. Repeated analyses of equivalent
traces therefore compare equal.

Malformed selections fail closed with categorized :class:`AutodiffError` values
rather than a raw container exception: ``ambiguous_producer`` when one value has
two producers or a declared seed collides with a forward value,
``invalid_selected_output`` when a selection is empty or names an unknown value,
``malformed_derivative_ir`` when the reachable region contains a cycle,
``missing_dependency`` when a reachable value has no producer and no provenance,
and ``missing_dtype_metadata`` / ``missing_shape_metadata`` when type metadata is
incomplete.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from typing import TYPE_CHECKING, Optional

from .protocol import AutodiffError
from .shape import typespec_ranked_shape

if TYPE_CHECKING:
    from .graph import TensorGraph, TensorNodeRecord
    from .reverse import DerivativeProgram


DEPENDENCY_PROVENANCE_DECLARED_INPUT = "declared_input"
DEPENDENCY_PROVENANCE_SEED_INPUT = "seed_input"
DEPENDENCY_PROVENANCE_FORWARD_CAPTURE = "forward_capture"
DEPENDENCY_PROVENANCE_LOCAL_VALUE = "local_value"

#: Documented grouping order of :attr:`DependencyAnalysis.dependencies`.
DEPENDENCY_PROVENANCE_ORDER: tuple[str, ...] = (
    DEPENDENCY_PROVENANCE_DECLARED_INPUT,
    DEPENDENCY_PROVENANCE_SEED_INPUT,
    DEPENDENCY_PROVENANCE_FORWARD_CAPTURE,
    DEPENDENCY_PROVENANCE_LOCAL_VALUE,
)


@dataclass(frozen=True)
class ValueDependency:
    """One analyzed value, its provenance, and its normalized type metadata.

    ``shape`` is the normalized ranked shape as a tuple of non-negative integer
    dimensions and symbolic dimension names. ``dtype`` and ``shape`` are ``None``
    only where the analyzed artifact records no metadata for the value at all;
    metadata that is present but incomplete fails closed instead.
    """

    value_id: str
    provenance: str
    dtype: Optional[str]
    shape: Optional[tuple[object, ...]]


@dataclass(frozen=True)
class DependencyAnalysis:
    """Deterministically ordered dependencies of a set of selected outputs."""

    selected_outputs: tuple[str, ...]
    dependencies: tuple[ValueDependency, ...]

    def with_provenance(self, provenance: str) -> tuple[ValueDependency, ...]:
        """Return the dependencies carrying *provenance*, in analysis order."""
        return tuple(
            dependency
            for dependency in self.dependencies
            if dependency.provenance == provenance
        )

    @property
    def declared_inputs(self) -> tuple[ValueDependency, ...]:
        return self.with_provenance(DEPENDENCY_PROVENANCE_DECLARED_INPUT)

    @property
    def seed_inputs(self) -> tuple[ValueDependency, ...]:
        return self.with_provenance(DEPENDENCY_PROVENANCE_SEED_INPUT)

    @property
    def forward_captures(self) -> tuple[ValueDependency, ...]:
        return self.with_provenance(DEPENDENCY_PROVENANCE_FORWARD_CAPTURE)

    @property
    def local_values(self) -> tuple[ValueDependency, ...]:
        return self.with_provenance(DEPENDENCY_PROVENANCE_LOCAL_VALUE)

    @property
    def required_inputs(self) -> tuple[ValueDependency, ...]:
        """Every dependency the caller must bind before running the selection."""
        return tuple(
            dependency
            for dependency in self.dependencies
            if dependency.provenance != DEPENDENCY_PROVENANCE_LOCAL_VALUE
        )


def analyze_graph_dependencies(
    graph: "TensorGraph",
    *,
    outputs: Optional[Sequence[str]] = None,
) -> DependencyAnalysis:
    """Analyze the values a forward *graph* selection depends on.

    ``outputs`` defaults to the graph's own outputs. A forward graph has no
    seeds and no captures, so every dependency is either a declared input or a
    value produced inside the graph. Type metadata is required for every
    reachable value, matching typed-graph finalization.
    """
    producers = _producers_by_value(graph.nodes, label="graph")
    declared_typespecs = _declared_typespecs(graph, label="graph")
    selected_outputs = _resolve_selected_outputs(
        outputs,
        default_outputs=graph.outputs,
        producers=producers,
        known_values=declared_typespecs.keys(),
    )
    reachable_nodes, free_value_ids = _reachable_region(selected_outputs, producers)

    for value_id in free_value_ids:
        if value_id not in declared_typespecs:
            raise AutodiffError(
                "missing_dependency",
                f"value {value_id!r} is reachable from the selected outputs "
                "but has no producing node and is not a declared graph input",
            )

    dependencies: list[ValueDependency] = []
    for value_id, typespec in graph.inputs:
        if value_id in free_value_ids:
            dependencies.append(
                _dependency(
                    value_id,
                    DEPENDENCY_PROVENANCE_DECLARED_INPUT,
                    typespec,
                    label=f"graph input {value_id!r}",
                    is_required=True,
                )
            )
    for node in reachable_nodes:
        dependencies.append(
            _dependency(
                node.output_value_id,
                DEPENDENCY_PROVENANCE_LOCAL_VALUE,
                node.output_typespec,
                label=f"node {node.node_id!r} output",
                is_required=True,
            )
        )
    return DependencyAnalysis(
        selected_outputs=selected_outputs,
        dependencies=tuple(dependencies),
    )


def analyze_derivative_dependencies(
    program: "DerivativeProgram",
    *,
    forward_graph: "TensorGraph",
    seed_value_ids: Sequence[str],
    outputs: Optional[Sequence[str]] = None,
) -> DependencyAnalysis:
    """Analyze the values a derivative *program* selection depends on.

    ``forward_graph`` is the traced graph the program was generated from and
    ``seed_value_ids`` are the upstream cotangent values the transform
    introduced. Both are required: without them a genuinely missing dependency
    would be indistinguishable from a seed, and the analysis could not fail
    closed. ``outputs`` defaults to the program's output gradients.

    Metadata is resolved from the program's recorded value typespecs first, then
    from the derivative nodes, then from the forward graph.
    """
    seeds = _resolve_seed_value_ids(seed_value_ids)
    forward_producers = _producers_by_value(forward_graph.nodes, label="forward graph")
    declared_typespecs = _declared_typespecs(forward_graph, label="forward graph")
    for seed_value_id in seeds:
        if seed_value_id in forward_producers or seed_value_id in declared_typespecs:
            raise AutodiffError(
                "ambiguous_producer",
                f"seed value {seed_value_id!r} is also a forward graph value, "
                "so its provenance is ambiguous",
            )

    producers = _producers_by_value(program.nodes, label="derivative program")
    known_values = set(seeds) | set(declared_typespecs) | set(forward_producers)
    selected_outputs = _resolve_selected_outputs(
        outputs,
        default_outputs=program.output_gradients,
        producers=producers,
        known_values=known_values,
    )
    reachable_nodes, free_value_ids = _reachable_region(selected_outputs, producers)

    for value_id in free_value_ids:
        if value_id not in known_values:
            raise AutodiffError(
                "missing_dependency",
                f"value {value_id!r} is reachable from the selected outputs but is "
                "neither produced by the derivative program, nor a declared seed, "
                "nor a value of the forward graph",
            )

    typespecs = _derivative_typespecs(program, forward_graph)

    dependencies: list[ValueDependency] = []
    for value_id in declared_typespecs:
        if value_id in free_value_ids:
            dependencies.append(
                _dependency(
                    value_id,
                    DEPENDENCY_PROVENANCE_DECLARED_INPUT,
                    typespecs.get(value_id),
                    label=f"declared input {value_id!r}",
                    is_required=False,
                )
            )
    for value_id in seeds:
        if value_id in free_value_ids:
            dependencies.append(
                _dependency(
                    value_id,
                    DEPENDENCY_PROVENANCE_SEED_INPUT,
                    typespecs.get(value_id),
                    label=f"seed input {value_id!r}",
                    is_required=False,
                )
            )
    for node in _topological_nodes(forward_graph):
        value_id = node.output_value_id
        if value_id in free_value_ids:
            dependencies.append(
                _dependency(
                    value_id,
                    DEPENDENCY_PROVENANCE_FORWARD_CAPTURE,
                    typespecs.get(value_id),
                    label=f"forward capture {value_id!r}",
                    is_required=False,
                )
            )
    for node in reachable_nodes:
        dependencies.append(
            _dependency(
                node.output_value_id,
                DEPENDENCY_PROVENANCE_LOCAL_VALUE,
                typespecs.get(node.output_value_id),
                label=f"derivative node {node.node_id!r} output",
                is_required=False,
            )
        )
    return DependencyAnalysis(
        selected_outputs=selected_outputs,
        dependencies=tuple(dependencies),
    )


def _resolve_seed_value_ids(seed_value_ids: Sequence[str]) -> tuple[str, ...]:
    """Normalize declared seed ids, preserving caller order and dropping repeats."""
    if isinstance(seed_value_ids, (str, bytes)) or not isinstance(seed_value_ids, Sequence):
        raise TypeError("seed_value_ids must be a non-string sequence of value ids")
    resolved: list[str] = []
    for seed_value_id in seed_value_ids:
        if not isinstance(seed_value_id, str) or not seed_value_id:
            raise TypeError("seed value ids must be non-empty strings")
        if seed_value_id not in resolved:
            resolved.append(seed_value_id)
    return tuple(resolved)


def _producers_by_value(
    nodes: Sequence["TensorNodeRecord"],
    *,
    label: str,
) -> dict[str, "TensorNodeRecord"]:
    """Index nodes by produced value, rejecting a value with two producers."""
    producers: dict[str, "TensorNodeRecord"] = {}
    for node in nodes:
        existing = producers.get(node.output_value_id)
        if existing is not None:
            raise AutodiffError(
                "ambiguous_producer",
                f"{label} value {node.output_value_id!r} is produced by both "
                f"node {existing.node_id!r} and node {node.node_id!r}",
            )
        producers[node.output_value_id] = node
    return producers


def _declared_typespecs(graph: "TensorGraph", *, label: str) -> dict[str, object]:
    """Index the declared graph inputs by value id, rejecting a repeated id.

    Mirrors :func:`_producers_by_value` for the other class of input: one value
    id must have exactly one provenance. A repeated declaration would otherwise
    either report a single id twice with contradicting metadata or collapse
    last-wins, and a consumer could not bind it from provenance alone.
    """
    declared: dict[str, object] = {}
    for value_id, typespec in graph.inputs:
        if value_id in declared:
            raise AutodiffError(
                "ambiguous_producer",
                f"{label} value {value_id!r} is declared as an input more than once",
            )
        declared[value_id] = typespec
    return declared


def _resolve_selected_outputs(
    outputs: Optional[Sequence[str]],
    *,
    default_outputs: Sequence[object],
    producers: Mapping[str, "TensorNodeRecord"],
    known_values: object,
) -> tuple[str, ...]:
    """Normalize and validate the explicitly selected outputs."""
    candidates = default_outputs if outputs is None else outputs
    if isinstance(candidates, (str, bytes)) or not isinstance(candidates, Sequence):
        raise AutodiffError(
            "invalid_selected_output",
            "selected outputs must be a non-string sequence of value ids",
        )

    resolved: list[str] = []
    for candidate in candidates:
        if not isinstance(candidate, str) or not candidate:
            raise AutodiffError(
                "invalid_selected_output",
                f"selected output {candidate!r} is not a non-empty value id",
            )
        if candidate not in resolved:
            resolved.append(candidate)

    if not resolved:
        raise AutodiffError(
            "invalid_selected_output",
            "dependency analysis requires at least one explicitly selected output",
        )

    for value_id in resolved:
        if value_id not in producers and value_id not in known_values:
            raise AutodiffError(
                "invalid_selected_output",
                f"selected output {value_id!r} is not produced by any node and is not a known value",
            )
    return tuple(resolved)


def _reachable_region(
    selected_outputs: Sequence[str],
    producers: Mapping[str, "TensorNodeRecord"],
) -> tuple[list["TensorNodeRecord"], set[str]]:
    """Return the reachable nodes in topological order plus the reachable free values."""
    ordered: list["TensorNodeRecord"] = []
    visited: set[str] = set()
    visiting: set[str] = set()
    free_value_ids: set[str] = set()

    def visit(value_id: str) -> None:
        node = producers.get(value_id)
        if node is None:
            free_value_ids.add(value_id)
            return
        if node.node_id in visited:
            return
        if node.node_id in visiting:
            raise AutodiffError(
                "malformed_derivative_ir",
                f"cycle detected while traversing node {node.node_id!r}",
            )
        visiting.add(node.node_id)
        for input_value_id in node.input_value_ids:
            visit(input_value_id)
        visiting.discard(node.node_id)
        visited.add(node.node_id)
        ordered.append(node)

    for value_id in selected_outputs:
        visit(value_id)
    return ordered, free_value_ids


def _topological_nodes(graph: "TensorGraph") -> list["TensorNodeRecord"]:
    """Return every node of *graph* in topological order."""
    producers = _producers_by_value(graph.nodes, label="forward graph")
    ordered, _free_value_ids = _reachable_region(
        [node.output_value_id for node in graph.nodes], producers
    )
    return ordered


def _derivative_typespecs(
    program: "DerivativeProgram",
    forward_graph: "TensorGraph",
) -> dict[str, object]:
    """Collect the type metadata available for a derivative program's values."""
    typespecs: dict[str, object] = {}
    for value_id, typespec in forward_graph.inputs:
        if typespec is not None:
            typespecs[value_id] = typespec
    for node in forward_graph.nodes:
        if node.output_typespec is not None:
            typespecs[node.output_value_id] = node.output_typespec
    for node in program.nodes:
        if node.output_typespec is not None:
            typespecs[node.output_value_id] = node.output_typespec
    for value_id, typespec in program.value_typespecs.items():
        if typespec is not None:
            typespecs[value_id] = typespec
    return typespecs


def _dependency(
    value_id: str,
    provenance: str,
    typespec: object,
    *,
    label: str,
    is_required: bool,
) -> ValueDependency:
    """Build one dependency, validating whatever type metadata is available.

    ``is_required`` demands complete metadata, as typed forward graphs
    guarantee. Where metadata is absent from a best-effort artifact the
    dependency reports ``None``, but metadata that is present must still be
    complete.
    """
    if typespec is None and not is_required:
        return ValueDependency(
            value_id=value_id, provenance=provenance, dtype=None, shape=None
        )
    dtype, shape = _complete_typespec(typespec, label=label)
    return ValueDependency(
        value_id=value_id, provenance=provenance, dtype=dtype, shape=shape
    )


def _complete_typespec(typespec: object, *, label: str) -> tuple[str, tuple[object, ...]]:
    """Return the dtype and normalized ranked shape, failing closed if incomplete."""
    if (
        not isinstance(typespec, Mapping)
        or not isinstance(typespec.get("dtype"), str)
        or not typespec["dtype"]
    ):
        raise AutodiffError("missing_dtype_metadata", f"{label} is missing dtype metadata")
    try:
        # Absent, unranked, and malformed shapes all become the documented
        # category; a raw container exception must never escape analysis.
        shape = typespec_ranked_shape({"shape": typespec.get("shape")})
    except AutodiffError:
        raise
    except (IndexError, TypeError, ValueError) as exc:
        raise AutodiffError(
            "missing_shape_metadata", f"{label} is missing ranked shape metadata"
        ) from exc
    return str(typespec["dtype"]), tuple(shape)
