"""Structured dependency analysis for selected forward and derivative outputs.

A consumer that wants to run a generated derivative program must bind one value
for every free input of that program. Discovering those inputs by scanning graph
nodes, consulting a private producer map, or reading meaning into how a value id
happens to be spelled makes the consumer responsible for graph mechanics that
belong to the framework. This module owns that responsibility instead.

Analysis starts from explicitly selected outputs, traverses only the nodes those
outputs reach, and reports every value the selection depends on together with a
provenance category and normalized type metadata:

``declared_input``
    A value the forward trace declared as a named graph input. The consumer
    supplies it (parameters, training data, labels).
``seed_input``
    An upstream cotangent generated by the derivative transform. The consumer
    supplies it, typically as ones shaped like the differentiated output.
``forward_capture``
    An intermediate produced by the forward graph and consumed again by the
    derivative program. The consumer must execute the forward graph and retain
    it before running the derivative program.
``local_value``
    A value produced inside the analyzed selection itself. Nothing to bind.

Provenance is decided structurally, from where a value is produced relative to
the forward graph and the declared seeds, never from its id text. Ordering is
deterministic and documented: dependencies are grouped in
:data:`DEPENDENCY_PROVENANCE_ORDER`, declared inputs follow forward-graph
declaration order, seeds follow the order the caller declared them, forward
captures follow forward-graph topological order, and local values follow the
analyzed selection's schedule -- topologically valid, with each operation
emitted as late as its consumers allow so that a producer stays beside the
operation that reads it (see :func:`_order_reachable_nodes` for the rule and
its tie-break). Repeated analyses of equivalent traces therefore compare
equal.

One value id must have exactly one provenance, and that invariant is enforced
in one place rather than per index. A single assignment pass walks the reachable
set and assigns each value its provenance; assigning a second provenance to an
id that already has one raises ``ambiguous_producer`` naming the id and both
conflicting categories. Every pairing -- two declarations, a declaration that is
also produced, a seed that collides with a declared input or with a produced
forward value -- therefore fails through the same check, which cannot be
partially applied.

Malformed selections fail closed with categorized :class:`AutodiffError` values
rather than a raw container exception: ``ambiguous_producer`` when one value
would carry two provenances or two nodes produce the same value,
``invalid_selected_output`` when a selection is empty or names an unknown value,
``malformed_derivative_ir`` when a cycle is found -- reachability-scoped for a
forward graph and for the derivative program itself, but for the forward-graph
half of a derivative-program analysis gated on whether the selection captures
anything from the forward graph at all, not on whether a given cycle is
reachable (see the comment at the forward-capture check in
``analyze_derivative_dependencies`` for the exact boundary),
``missing_dependency`` when a reachable value has no producer and no provenance,
and ``missing_dtype_metadata`` / ``missing_shape_metadata`` when type metadata is
incomplete.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from typing import TYPE_CHECKING, Optional

from .protocol import AutodiffError
from .shape import typespec_ranked_shape

if TYPE_CHECKING:
    from .graph import TensorGraph, TensorNodeRecord
    from .reverse import DerivativeProgram


DEPENDENCY_PROVENANCE_DECLARED_INPUT = "declared_input"
DEPENDENCY_PROVENANCE_SEED_INPUT = "seed_input"
DEPENDENCY_PROVENANCE_FORWARD_CAPTURE = "forward_capture"
DEPENDENCY_PROVENANCE_LOCAL_VALUE = "local_value"

#: Documented grouping order of :attr:`DependencyAnalysis.dependencies`.
DEPENDENCY_PROVENANCE_ORDER: tuple[str, ...] = (
    DEPENDENCY_PROVENANCE_DECLARED_INPUT,
    DEPENDENCY_PROVENANCE_SEED_INPUT,
    DEPENDENCY_PROVENANCE_FORWARD_CAPTURE,
    DEPENDENCY_PROVENANCE_LOCAL_VALUE,
)


@dataclass(frozen=True)
class ValueDependency:
    """One analyzed value, its provenance, and its normalized type metadata.

    ``shape`` is the normalized ranked shape as a tuple of non-negative integer
    dimensions and symbolic dimension names. ``dtype`` and ``shape`` are ``None``
    only where the analyzed artifact records no metadata for the value at all;
    metadata that is present but incomplete fails closed instead.
    """

    value_id: str
    provenance: str
    dtype: Optional[str]
    shape: Optional[tuple[object, ...]]


@dataclass(frozen=True)
class DependencyAnalysis:
    """Deterministically ordered dependencies of a set of selected outputs."""

    selected_outputs: tuple[str, ...]
    dependencies: tuple[ValueDependency, ...]

    def with_provenance(self, provenance: str) -> tuple[ValueDependency, ...]:
        """Return the dependencies carrying *provenance*, in analysis order."""
        return tuple(
            dependency
            for dependency in self.dependencies
            if dependency.provenance == provenance
        )

    @property
    def declared_inputs(self) -> tuple[ValueDependency, ...]:
        return self.with_provenance(DEPENDENCY_PROVENANCE_DECLARED_INPUT)

    @property
    def seed_inputs(self) -> tuple[ValueDependency, ...]:
        return self.with_provenance(DEPENDENCY_PROVENANCE_SEED_INPUT)

    @property
    def forward_captures(self) -> tuple[ValueDependency, ...]:
        return self.with_provenance(DEPENDENCY_PROVENANCE_FORWARD_CAPTURE)

    @property
    def local_values(self) -> tuple[ValueDependency, ...]:
        return self.with_provenance(DEPENDENCY_PROVENANCE_LOCAL_VALUE)

    @property
    def required_inputs(self) -> tuple[ValueDependency, ...]:
        """Every dependency the caller must bind before running the selection."""
        return tuple(
            dependency
            for dependency in self.dependencies
            if dependency.provenance != DEPENDENCY_PROVENANCE_LOCAL_VALUE
        )


def analyze_graph_dependencies(
    graph: "TensorGraph",
    *,
    outputs: Optional[Sequence[str]] = None,
) -> DependencyAnalysis:
    """Analyze the values a forward *graph* selection depends on.

    ``outputs`` defaults to the graph's own outputs. A forward graph has no
    seeds and no captures, so every dependency is either a declared input or a
    value produced inside the graph. Type metadata is required for every
    reachable value, matching typed-graph finalization.
    """
    producers = _producers_by_value(graph.nodes, label="graph")
    declared_typespecs = _declared_typespecs(graph)
    selected_outputs = _resolve_selected_outputs(
        outputs,
        default_outputs=graph.outputs,
        producers=producers,
        known_values=declared_typespecs.keys(),
    )
    reachable_nodes, free_value_ids = _reachable_region(selected_outputs, producers)

    assignments: dict[str, str] = {}
    reachable_values = free_value_ids | {node.output_value_id for node in reachable_nodes}
    # Iterate the declared inputs themselves, not the index built from them, so
    # a value declared twice is two assignments rather than one dict entry.
    for value_id, _typespec in graph.inputs:
        if value_id in reachable_values:
            _assign_provenance(assignments, value_id, DEPENDENCY_PROVENANCE_DECLARED_INPUT)
    for node in reachable_nodes:
        _assign_provenance(
            assignments, node.output_value_id, DEPENDENCY_PROVENANCE_LOCAL_VALUE
        )

    for value_id in free_value_ids:
        if value_id not in assignments:
            raise AutodiffError(
                "missing_dependency",
                f"value {value_id!r} is reachable from the selected outputs "
                "but has no producing node and is not a declared graph input",
            )

    dependencies: list[ValueDependency] = []
    for value_id, typespec in graph.inputs:
        if value_id in free_value_ids:
            dependencies.append(
                _dependency(
                    value_id,
                    DEPENDENCY_PROVENANCE_DECLARED_INPUT,
                    typespec,
                    label=f"graph input {value_id!r}",
                    is_required=True,
                )
            )
    for node in reachable_nodes:
        dependencies.append(
            _dependency(
                node.output_value_id,
                DEPENDENCY_PROVENANCE_LOCAL_VALUE,
                node.output_typespec,
                label=f"node {node.node_id!r} output",
                is_required=True,
            )
        )
    return DependencyAnalysis(
        selected_outputs=selected_outputs,
        dependencies=tuple(dependencies),
    )


def analyze_derivative_dependencies(
    program: "DerivativeProgram",
    *,
    forward_graph: "TensorGraph",
    seed_value_ids: Sequence[str],
    outputs: Optional[Sequence[str]] = None,
) -> DependencyAnalysis:
    """Analyze the values a derivative *program* selection depends on.

    ``forward_graph`` is the traced graph the program was generated from and
    ``seed_value_ids`` are the upstream cotangent values the transform
    introduced. Both are required: without them a genuinely missing dependency
    would be indistinguishable from a seed, and the analysis could not fail
    closed. ``outputs`` defaults to the program's output gradients.

    Metadata is resolved from the program's recorded value typespecs first, then
    from the derivative nodes, then from the forward graph.
    """
    seeds = _resolve_seed_value_ids(seed_value_ids)
    forward_producers = _producers_by_value(forward_graph.nodes, label="forward graph")
    declared_typespecs = _declared_typespecs(forward_graph)
    producers = _producers_by_value(program.nodes, label="derivative program")
    known_values = set(seeds) | set(declared_typespecs) | set(forward_producers)
    selected_outputs = _resolve_selected_outputs(
        outputs,
        default_outputs=program.output_gradients,
        producers=producers,
        known_values=known_values,
    )
    reachable_nodes, free_value_ids = _reachable_region(selected_outputs, producers)

    assignments: dict[str, str] = {}
    reachable_values = free_value_ids | {node.output_value_id for node in reachable_nodes}
    # Iterate the declared inputs themselves, not the index built from them, so
    # a value declared twice is two assignments rather than one dict entry.
    for value_id, _typespec in forward_graph.inputs:
        if value_id in reachable_values:
            _assign_provenance(assignments, value_id, DEPENDENCY_PROVENANCE_DECLARED_INPUT)
    for value_id in seeds:
        if value_id in reachable_values:
            _assign_provenance(assignments, value_id, DEPENDENCY_PROVENANCE_SEED_INPUT)
    for node in forward_graph.nodes:
        if node.output_value_id in reachable_values:
            _assign_provenance(
                assignments, node.output_value_id, DEPENDENCY_PROVENANCE_FORWARD_CAPTURE
            )
    for node in reachable_nodes:
        _assign_provenance(
            assignments, node.output_value_id, DEPENDENCY_PROVENANCE_LOCAL_VALUE
        )

    for value_id in free_value_ids:
        if value_id not in assignments:
            raise AutodiffError(
                "missing_dependency",
                f"value {value_id!r} is reachable from the selected outputs but is "
                "neither produced by the derivative program, nor a declared seed, "
                "nor a value of the forward graph",
            )

    typespecs = _derivative_typespecs(program, forward_graph)

    dependencies: list[ValueDependency] = []
    for value_id in declared_typespecs:
        if value_id in free_value_ids:
            dependencies.append(
                _dependency(
                    value_id,
                    DEPENDENCY_PROVENANCE_DECLARED_INPUT,
                    typespecs.get(value_id),
                    label=f"declared input {value_id!r}",
                    is_required=False,
                )
            )
    for value_id in seeds:
        if value_id in free_value_ids:
            dependencies.append(
                _dependency(
                    value_id,
                    DEPENDENCY_PROVENANCE_SEED_INPUT,
                    typespecs.get(value_id),
                    label=f"seed input {value_id!r}",
                    is_required=False,
                )
            )
    has_forward_captures = any(
        assignments.get(value_id) == DEPENDENCY_PROVENANCE_FORWARD_CAPTURE
        for value_id in free_value_ids
    )
    if has_forward_captures:
        # This is also the only forward-graph cycle check: `_topological_nodes`
        # walks every node of `forward_graph`, not just the ones between a
        # capture and its consumer. The boundary this skip draws is therefore
        # gated on whether ANY forward value is captured, not on whether a
        # given cycle is reachable from one:
        #   - no capture at all  -> the forward graph is never walked, so a
        #     cycle anywhere in it, related or not, is not reported.
        #   - at least one capture -> the whole forward graph is walked, so
        #     every cycle in it is found, including one with no relationship
        #     to what was actually captured.
        # A precisely reachability-scoped cycle check (walk only from each
        # captured value) is a different, larger change and is not made here.
        for node in _topological_nodes(forward_graph):
            value_id = node.output_value_id
            if value_id in free_value_ids:
                dependencies.append(
                    _dependency(
                        value_id,
                        DEPENDENCY_PROVENANCE_FORWARD_CAPTURE,
                        typespecs.get(value_id),
                        label=f"forward capture {value_id!r}",
                        is_required=False,
                    )
                )
    for node in reachable_nodes:
        dependencies.append(
            _dependency(
                node.output_value_id,
                DEPENDENCY_PROVENANCE_LOCAL_VALUE,
                typespecs.get(node.output_value_id),
                label=f"derivative node {node.node_id!r} output",
                is_required=False,
            )
        )
    return DependencyAnalysis(
        selected_outputs=selected_outputs,
        dependencies=tuple(dependencies),
    )


def _resolve_seed_value_ids(seed_value_ids: Sequence[str]) -> tuple[str, ...]:
    """Normalize declared seed ids, preserving caller order and dropping repeats.

    Mirrors :func:`_resolve_selected_outputs`'s guard: a malformed shape here is
    exactly as much a caller-provided selection error as a malformed selected
    output, so it fails the same way, with the same category, rather than
    escaping as a raw container-type exception.
    """
    if isinstance(seed_value_ids, (str, bytes)) or not isinstance(seed_value_ids, Sequence):
        raise AutodiffError(
            "invalid_selected_output",
            "seed_value_ids must be a non-string sequence of value ids",
        )
    resolved: list[str] = []
    for seed_value_id in seed_value_ids:
        if not isinstance(seed_value_id, str) or not seed_value_id:
            raise AutodiffError(
                "invalid_selected_output",
                f"seed value id {seed_value_id!r} is not a non-empty value id",
            )
        if seed_value_id not in resolved:
            resolved.append(seed_value_id)
    return tuple(resolved)


def _producers_by_value(
    nodes: Sequence["TensorNodeRecord"],
    *,
    label: str,
) -> dict[str, "TensorNodeRecord"]:
    """Index nodes by produced value, rejecting a repeated node or value id.

    This check stays ahead of the provenance assignment pass rather than
    folding into it, because traversal is defined in terms of this index: with
    two producers for one value, the reachable set itself is ambiguous and the
    pass would only ever see whichever node the index kept.

    A repeated *node* id is rejected here for the same reason and in the same
    way. The reachable walk keys visited operations by node id, so two
    distinct operations sharing one id are conflated into one: independent
    duplicates make the walk skip the second silently, and the analysis then
    succeeds with an answer that reports one of the operations neither as a
    local value nor as a missing dependency -- a consumer binding from that
    answer builds a wrong program. Chained duplicates instead look like the
    walk re-entering an in-progress node and are reported as a cycle that does
    not exist. Both are one value id or node id standing for two things, which
    is what ``ambiguous_producer`` already means.
    """
    producers: dict[str, "TensorNodeRecord"] = {}
    nodes_by_id: dict[str, "TensorNodeRecord"] = {}
    for node in nodes:
        previous = nodes_by_id.get(node.node_id)
        if previous is not None:
            raise AutodiffError(
                "ambiguous_producer",
                f"{label} node id {node.node_id!r} identifies both the operation "
                f"producing value {previous.output_value_id!r} and the operation "
                f"producing value {node.output_value_id!r}",
            )
        nodes_by_id[node.node_id] = node
        existing = producers.get(node.output_value_id)
        if existing is not None:
            raise AutodiffError(
                "ambiguous_producer",
                f"{label} value {node.output_value_id!r} is produced by both "
                f"node {existing.node_id!r} and node {node.node_id!r}",
            )
        producers[node.output_value_id] = node
    return producers


def _assign_provenance(
    assignments: dict[str, str],
    value_id: str,
    provenance: str,
) -> None:
    """Give *value_id* its provenance, rejecting a value that already has one.

    This is the single point where the "one value id, one provenance" invariant
    is enforced. Checking it per index instead would leave every pairing of
    indices as its own possible gap; here a declaration that is also produced, a
    value declared twice, and a seed that collides with either all arrive at the
    same rejection.
    """
    existing = assignments.get(value_id)
    if existing is not None:
        if existing == provenance:
            raise AutodiffError(
                "ambiguous_producer",
                f"value {value_id!r} is assigned the {provenance!r} provenance more than once",
            )
        raise AutodiffError(
            "ambiguous_producer",
            f"value {value_id!r} has conflicting provenance: "
            f"{existing!r} and {provenance!r}",
        )
    assignments[value_id] = provenance


def _declared_typespecs(graph: "TensorGraph") -> dict[str, object]:
    """Index the declared graph inputs by value id, for metadata lookup.

    A repeated declaration is not rejected here: the provenance assignment pass
    walks ``graph.inputs`` directly and rejects it there, so that every
    ambiguity is reported by one check rather than by whichever index happened
    to notice first.
    """
    return {value_id: typespec for value_id, typespec in graph.inputs}


def _resolve_selected_outputs(
    outputs: Optional[Sequence[str]],
    *,
    default_outputs: Sequence[object],
    producers: Mapping[str, "TensorNodeRecord"],
    known_values: object,
) -> tuple[str, ...]:
    """Normalize and validate the explicitly selected outputs."""
    candidates = default_outputs if outputs is None else outputs
    if isinstance(candidates, (str, bytes)) or not isinstance(candidates, Sequence):
        raise AutodiffError(
            "invalid_selected_output",
            "selected outputs must be a non-string sequence of value ids",
        )

    resolved: list[str] = []
    for candidate in candidates:
        if not isinstance(candidate, str) or not candidate:
            raise AutodiffError(
                "invalid_selected_output",
                f"selected output {candidate!r} is not a non-empty value id",
            )
        if candidate not in resolved:
            resolved.append(candidate)

    if not resolved:
        raise AutodiffError(
            "invalid_selected_output",
            "dependency analysis requires at least one explicitly selected output",
        )

    for value_id in resolved:
        if value_id not in producers and value_id not in known_values:
            raise AutodiffError(
                "invalid_selected_output",
                f"selected output {value_id!r} is not produced by any node and is not a known value",
            )
    return tuple(resolved)


def _reachable_region(
    selected_outputs: Sequence[str],
    producers: Mapping[str, "TensorNodeRecord"],
) -> tuple[list["TensorNodeRecord"], set[str]]:
    """Return the reachable nodes in emitted order plus the reachable free values.

    Reachability (which nodes and free values the selection depends on, with
    cycle detection) and emission order are computed as two separate steps --
    :func:`_walk_reachable` decides the set, :func:`_order_reachable_nodes`
    only sequences it -- so a future change to traversal order can replace the
    ordering step alone without re-deriving reachability or cycle detection.
    """
    reachable_nodes, free_value_ids = _walk_reachable(selected_outputs, producers)
    ordered = _order_reachable_nodes(reachable_nodes)
    return ordered, free_value_ids


def _walk_reachable(
    selected_outputs: Sequence[str],
    producers: Mapping[str, "TensorNodeRecord"],
) -> tuple[dict[str, "TensorNodeRecord"], set[str]]:
    """Iteratively determine every node and free value reachable from *selected_outputs*.

    Uses an explicit worklist instead of recursion so a deep dependency chain
    does not exhaust the interpreter's recursion limit. A node is "in
    progress" from the moment its inputs begin traversal until every input has
    been fully resolved; encountering an in-progress node again means a cycle,
    detected and categorized exactly as the prior recursive walk did. The
    returned mapping's insertion order is a topological (post-order) order --
    each node is inserted only after every value it reads has been fully
    resolved -- but it is not the emitted order: :func:`_order_reachable_nodes`
    reschedules it. Callers that only need the set may ignore order; the
    ordering step relies on this one being topological, and on nothing else
    about it beyond its determinism.
    """
    reachable: dict[str, "TensorNodeRecord"] = {}
    free_value_ids: set[str] = set()
    in_progress: set[str] = set()
    # Reversed so the stack pops selected outputs in their original order --
    # the same order a `for value_id in selected_outputs: visit(value_id)`
    # recursive walk would visit them, matching how each node's own inputs
    # are pushed reversed below.
    stack: list[tuple[str, bool]] = [(value_id, False) for value_id in reversed(selected_outputs)]
    while stack:
        value_id, expanded = stack.pop()
        node = producers.get(value_id)
        if node is None:
            free_value_ids.add(value_id)
            continue
        if node.node_id in reachable:
            continue
        if expanded:
            in_progress.discard(node.node_id)
            reachable[node.node_id] = node
            continue
        if node.node_id in in_progress:
            raise AutodiffError(
                "malformed_derivative_ir",
                f"cycle detected while traversing node {node.node_id!r}",
            )
        in_progress.add(node.node_id)
        stack.append((value_id, True))
        for input_value_id in reversed(node.input_value_ids):
            stack.append((input_value_id, False))
    return reachable, free_value_ids


def _order_reachable_nodes(
    reachable_nodes: Mapping[str, "TensorNodeRecord"],
) -> list["TensorNodeRecord"]:
    """Sequence an already-computed reachable set into the documented order.

    Deliberately takes only the reachable mapping, not the selection or the
    producer index that decided it, so this function can only reorder the
    given set -- it has no way to add or drop a node. Isolated from
    :func:`_walk_reachable` so a traversal-order change replaces this function
    alone. The producer relation used below is rebuilt from the given mapping
    itself, so that boundary holds.

    Latest legal position
    ---------------------
    Each operation is emitted as late as its consumers allow rather than as
    early as its producers allow. Emitting early puts a producer at the front
    of the region, separated from the operation that reads it by unrelated
    work; emitting late leaves the two adjacent whenever nothing forces them
    apart. Adjacency is what a consumer's bounded look-ahead window needs in
    order to see a producer and its consumer together, so this is the ordering
    that makes a local fusion -- a transpose folded into the matmul that reads
    it -- expressible at all.

    The order is built back to front. An operation is *ready* once every
    operation in the set that reads its output has already been placed; the
    ready operation chosen next is placed immediately before everything
    already placed, and its own producers are then released.

    Tie-break
    ---------
    Several operations are often ready at once, and the choice between them is
    what decides which producer ends up adjacent to its consumer, so it is
    fixed by rule rather than left to iteration order:

    1. Prefer the shortest chain of producers within the set. A long chain
       needs the most room ahead of it, so it is placed earliest; a short one
       can wait beside its consumer.
    2. Among equal chains, prefer the operation released most recently -- that
       is, by the operation just placed -- which keeps a producer beside the
       consumer that released it.
    3. A consumer releases its producers in reverse operand order, and the
       operations that begin ready are seeded in the set's own discovery
       order, so rule 2 resolves to the first operand and to discovery order
       respectively when nothing else separates the candidates.

    Rule 1 is not the obvious rule, and the obvious one is wrong. A plain
    reverse pass that simply follows operands merely inverts which case fails:
    the derivative programs for two different differentiated parameters of one
    expression are the same operations differing only in a matmul's operand
    order, so any rule keyed on operand position keeps one of them working by
    breaking the other. Chain length is a property of the graph rather than of
    how one operation happens to spell its operands, which is why it separates
    the two cases identically.

    Every input to the rule -- chain length, release order, discovery order --
    is derived from the given mapping's insertion order and each operation's
    recorded operands. Nothing reads set iteration order, dictionary ordering
    that is not insertion-stable, hash values, or object identity, so
    equivalent graphs are sequenced identically in any interpreter.
    """
    nodes = list(reachable_nodes.values())
    producer_of_output = {node.output_value_id: node for node in nodes}

    def producers_of(node: "TensorNodeRecord") -> list["TensorNodeRecord"]:
        """The distinct operations in this set producing *node*'s operands."""
        found: list["TensorNodeRecord"] = []
        seen: set[str] = set()
        for value_id in node.input_value_ids:
            producer = producer_of_output.get(value_id)
            if producer is None or producer.node_id in seen:
                continue
            seen.add(producer.node_id)
            found.append(producer)
        return found

    # The mapping's insertion order is topological, so one forward pass is
    # enough to measure how long a chain of producers ends at each node. That
    # is also the only assumption this function makes about the order it is
    # given, so it is checked here rather than assumed: a producer not yet
    # measured means the order was not topological, which means a cycle. The
    # reachability walk rejects a cycle before this function is called, so the
    # check is unreachable through the public entry points -- but sequencing a
    # cyclic set would otherwise strand operations, and emitting the rest
    # would be a program in an order no consumer can run.
    chain_length: dict[str, int] = {}
    unplaced_consumers: dict[str, int] = {node.node_id: 0 for node in nodes}
    for node in nodes:
        producers = producers_of(node)
        for producer in producers:
            if producer.node_id not in chain_length:
                raise AutodiffError(
                    "malformed_derivative_ir",
                    f"the reachable operations cannot be sequenced: operation "
                    f"{node.node_id!r} reads a value produced by {producer.node_id!r}, "
                    "which is part of a cycle",
                )
            unplaced_consumers[producer.node_id] += 1
        chain_length[node.node_id] = max(
            (chain_length[producer.node_id] + 1 for producer in producers),
            default=0,
        )

    ready = [node for node in nodes if unplaced_consumers[node.node_id] == 0]
    placed: list["TensorNodeRecord"] = []
    while ready:
        # Scanning from the end keeps the most recently released candidate
        # unless an earlier one has a strictly shorter chain, which is rule 2
        # applied only where rule 1 leaves a tie.
        chosen = len(ready) - 1
        for index in range(len(ready) - 2, -1, -1):
            if chain_length[ready[index].node_id] < chain_length[ready[chosen].node_id]:
                chosen = index
        node = ready.pop(chosen)
        placed.append(node)

        released: list["TensorNodeRecord"] = []
        for producer in producers_of(node):
            unplaced_consumers[producer.node_id] -= 1
            if unplaced_consumers[producer.node_id] == 0:
                released.append(producer)
        ready.extend(reversed(released))

    # Every operation is placed: the order above is known to be topological,
    # and releasing a producer only once its last consumer is placed always
    # terminates having placed the whole set.
    placed.reverse()
    return placed


def _topological_nodes(graph: "TensorGraph") -> list["TensorNodeRecord"]:
    """Return every node of *graph* in topological order."""
    producers = _producers_by_value(graph.nodes, label="forward graph")
    ordered, _free_value_ids = _reachable_region(
        [node.output_value_id for node in graph.nodes], producers
    )
    return ordered


def _derivative_typespecs(
    program: "DerivativeProgram",
    forward_graph: "TensorGraph",
) -> dict[str, object]:
    """Collect the type metadata available for a derivative program's values."""
    typespecs: dict[str, object] = {}
    for value_id, typespec in forward_graph.inputs:
        if typespec is not None:
            typespecs[value_id] = typespec
    for node in forward_graph.nodes:
        if node.output_typespec is not None:
            typespecs[node.output_value_id] = node.output_typespec
    for node in program.nodes:
        if node.output_typespec is not None:
            typespecs[node.output_value_id] = node.output_typespec
    for value_id, typespec in program.value_typespecs.items():
        if typespec is not None:
            typespecs[value_id] = typespec
    return typespecs


def _dependency(
    value_id: str,
    provenance: str,
    typespec: object,
    *,
    label: str,
    is_required: bool,
) -> ValueDependency:
    """Build one dependency, validating whatever type metadata is available.

    ``is_required`` demands complete metadata, as typed forward graphs
    guarantee. Where metadata is absent from a best-effort artifact the
    dependency reports ``None``, but metadata that is present must still be
    complete.
    """
    if typespec is None and not is_required:
        return ValueDependency(
            value_id=value_id, provenance=provenance, dtype=None, shape=None
        )
    dtype, shape = _complete_typespec(typespec, label=label)
    return ValueDependency(
        value_id=value_id, provenance=provenance, dtype=dtype, shape=shape
    )


def _complete_typespec(typespec: object, *, label: str) -> tuple[str, tuple[object, ...]]:
    """Return the dtype and normalized ranked shape, failing closed if incomplete."""
    if (
        not isinstance(typespec, Mapping)
        or not isinstance(typespec.get("dtype"), str)
        or not typespec["dtype"]
    ):
        raise AutodiffError("missing_dtype_metadata", f"{label} is missing dtype metadata")
    try:
        # Absent, unranked, and malformed shapes all become the documented
        # category; a raw container exception must never escape analysis.
        shape = typespec_ranked_shape({"shape": typespec.get("shape")})
    except AutodiffError:
        raise
    except (IndexError, TypeError, ValueError) as exc:
        raise AutodiffError(
            "missing_shape_metadata", f"{label} is missing ranked shape metadata"
        ) from exc
    return str(typespec["dtype"]), tuple(shape)
